# Generated by Django 2.2 on 2019-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topheadline',
            name='likes',
            field=models.IntegerField(default=13588),
        ),
        migrations.AlterField(
            model_name='topheadline',
            name='publishedAt',
            field=models.DateTimeField(),
        ),
    ]
