# Generated by Django 2.2 on 2019-06-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20190605_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topheadline',
            name='is_true',
        ),
        migrations.RemoveField(
            model_name='topheadline',
            name='is_true_prob',
        ),
    ]
