// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weblog.Models;

namespace weblog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("weblog.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ShortDescription = "Medium's largest active publications about Tech. Follow us to join our community.",
                            Title = "Tech"
                        },
                        new
                        {
                            CategoryId = 2,
                            ShortDescription = "Medium's largest active publications about Politics. Follow us to join our community.",
                            Title = "Politics"
                        },
                        new
                        {
                            CategoryId = 3,
                            ShortDescription = "Medium's largest active publications about Life. Follow us to join our community.",
                            Title = "Life"
                        },
                        new
                        {
                            CategoryId = 4,
                            ShortDescription = "Medium's largest active publications about Science. Follow us to join our community.",
                            Title = "Science"
                        },
                        new
                        {
                            CategoryId = 5,
                            ShortDescription = "Medium's largest active publications about Sport. Follow us to join our community.",
                            Title = "Sport"
                        },
                        new
                        {
                            CategoryId = 7,
                            ShortDescription = "Medium's largest active publications about Zen. Follow us to join our community.",
                            Title = "Zen"
                        });
                });

            modelBuilder.Entity("weblog.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Date")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("weblog.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Claps")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("InSandbox")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForSubscribersOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TimeToRead")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PostId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(2244),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 792, DateTimeKind.Local).AddTicks(6025),
                            ImageUrl = "https://localhost:5001/Images/image1.jpg",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Autonomous Driving Updates, HyperAutomation, and More",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Here Is A Rundown of 5 Major Tech Trends Hitting 2020"
                        },
                        new
                        {
                            PostId = 2,
                            CategoryId = 2,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4097),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4077),
                            ImageUrl = "https://source.unsplash.com/random/800x501",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 3,
                            CategoryId = 2,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4180),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4178),
                            ImageUrl = "https://source.unsplash.com/random/800x502",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 4,
                            CategoryId = 2,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4204),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4201),
                            ImageUrl = "https://source.unsplash.com/random/800x503",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 5,
                            CategoryId = 2,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4226),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4224),
                            ImageUrl = "https://source.unsplash.com/random/800x504",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 6,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4252),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4250),
                            ImageUrl = "https://source.unsplash.com/random/800x505",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 7,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4273),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4271),
                            ImageUrl = "https://source.unsplash.com/random/800x500",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 8,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4295),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4292),
                            ImageUrl = "https://source.unsplash.com/random/800x507",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 9,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4316),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4314),
                            ImageUrl = "https://source.unsplash.com/random/800x508",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 10,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4339),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4337),
                            ImageUrl = "https://source.unsplash.com/random/800x510",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 11,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4360),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4358),
                            ImageUrl = "https://source.unsplash.com/random/800x511",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 12,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4381),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4379),
                            ImageUrl = "https://source.unsplash.com/random/800x512",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 13,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4401),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4399),
                            ImageUrl = "https://source.unsplash.com/random/800x513",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 14,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4422),
                            DatePosted = new DateTime(2019, 12, 19, 23, 58, 9, 796, DateTimeKind.Local).AddTicks(4420),
                            ImageUrl = "https://source.unsplash.com/random/800x514",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        });
                });

            modelBuilder.Entity("weblog.Models.Post", b =>
                {
                    b.HasOne("weblog.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
