// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weblog.Models;

namespace weblog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("weblog.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Title = "Tech"
                        },
                        new
                        {
                            CategoryId = 2,
                            Title = "Politics"
                        },
                        new
                        {
                            CategoryId = 3,
                            Title = "Life"
                        },
                        new
                        {
                            CategoryId = 4,
                            Title = "Science"
                        },
                        new
                        {
                            CategoryId = 5,
                            Title = "Sport"
                        },
                        new
                        {
                            CategoryId = 7,
                            Title = "Zen"
                        });
                });

            modelBuilder.Entity("weblog.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Claps")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("InSandbox")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForSubscribersOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TimeToRead")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PostId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(1953),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 251, DateTimeKind.Local).AddTicks(3558),
                            ImageUrl = "~/Images/image1.jpg",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Autonomous Driving Updates, HyperAutomation, and More",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Here Is A Rundown of 5 Major Tech Trends Hitting 2020"
                        },
                        new
                        {
                            PostId = 2,
                            CategoryId = 2,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4227),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4203),
                            ImageUrl = "https://source.unsplash.com/random/800x501",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 3,
                            CategoryId = 2,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4319),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4317),
                            ImageUrl = "https://source.unsplash.com/random/800x502",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 4,
                            CategoryId = 2,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4344),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4342),
                            ImageUrl = "https://source.unsplash.com/random/800x503",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 5,
                            CategoryId = 2,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4367),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4365),
                            ImageUrl = "https://source.unsplash.com/random/800x504",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 6,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4396),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4394),
                            ImageUrl = "https://source.unsplash.com/random/800x505",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 7,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4417),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4415),
                            ImageUrl = "https://source.unsplash.com/random/800x500",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 8,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4438),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4436),
                            ImageUrl = "https://source.unsplash.com/random/800x507",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 9,
                            CategoryId = 1,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4459),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4457),
                            ImageUrl = "https://source.unsplash.com/random/800x508",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 10,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4483),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4480),
                            ImageUrl = "https://source.unsplash.com/random/800x510",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 11,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4504),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4502),
                            ImageUrl = "https://source.unsplash.com/random/800x511",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 12,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4525),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4523),
                            ImageUrl = "https://source.unsplash.com/random/800x512",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 13,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4546),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4544),
                            ImageUrl = "https://source.unsplash.com/random/800x513",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 14,
                            CategoryId = 3,
                            Claps = 0,
                            DateChanged = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4567),
                            DatePosted = new DateTime(2019, 12, 16, 23, 10, 28, 255, DateTimeKind.Local).AddTicks(4564),
                            ImageUrl = "https://source.unsplash.com/random/800x514",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            TimeToRead = 0,
                            Title = "Lorem Ipsum"
                        });
                });

            modelBuilder.Entity("weblog.Models.Post", b =>
                {
                    b.HasOne("weblog.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
