// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weblog.Models;

namespace weblog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("weblog.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Title = "Tech"
                        },
                        new
                        {
                            CategoryId = 2,
                            Title = "Politics"
                        },
                        new
                        {
                            CategoryId = 3,
                            Title = "Life"
                        },
                        new
                        {
                            CategoryId = 4,
                            Title = "Science"
                        },
                        new
                        {
                            CategoryId = 5,
                            Title = "Sport"
                        },
                        new
                        {
                            CategoryId = 7,
                            Title = "Zen"
                        });
                });

            modelBuilder.Entity("weblog.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("InSandbox")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForSubscribersOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PostId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            CategoryId = 1,
                            DateChanged = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(5430),
                            DatePosted = new DateTime(2019, 12, 12, 23, 56, 53, 897, DateTimeKind.Local).AddTicks(45),
                            ImageUrl = "~/Images/image1.jpg",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Autonomous Driving Updates, HyperAutomation, and More",
                            Text = "",
                            Title = "Here Is A Rundown of 5 Major Tech Trends Hitting 2020"
                        },
                        new
                        {
                            PostId = 2,
                            CategoryId = 2,
                            DateChanged = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(7526),
                            DatePosted = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(7507),
                            ImageUrl = "~/Images/image2.jpg",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 3,
                            CategoryId = 2,
                            DateChanged = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(7607),
                            DatePosted = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(7605),
                            ImageUrl = "~/Images/image3.jpg",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 4,
                            CategoryId = 2,
                            DateChanged = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(7629),
                            DatePosted = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(7627),
                            ImageUrl = "~/Images/image4.jpg",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            Title = "Lorem Ipsum"
                        },
                        new
                        {
                            PostId = 5,
                            CategoryId = 2,
                            DateChanged = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(7651),
                            DatePosted = new DateTime(2019, 12, 12, 23, 56, 53, 901, DateTimeKind.Local).AddTicks(7649),
                            ImageUrl = "~/Images/image5.jpg",
                            InSandbox = true,
                            IsForSubscribersOnly = false,
                            IsLocked = false,
                            ShortDescription = "Lorem ipsum dolor sit amet",
                            Text = "",
                            Title = "Lorem Ipsum"
                        });
                });

            modelBuilder.Entity("weblog.Models.Post", b =>
                {
                    b.HasOne("weblog.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
