# Generated by Django 2.2 on 2019-05-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_topheadline_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topheadline',
            name='content',
        ),
    ]
