# Generated by Django 2.2.1 on 2019-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_topheadline_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topheadline',
            name='is_fan',
            field=models.BooleanField(default=False),
        ),
    ]
