# Generated by Django 2.2.1 on 2019-06-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_topheadline_is_fan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topheadline',
            name='is_fan',
        ),
    ]
