# Generated by Django 2.2 on 2019-06-04 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0008_topheadline_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topheadline',
            name='favourites',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
