# Generated by Django 2.2 on 2019-06-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190605_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadline',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
